SELECT TOP (1000) [RollNumber]
      ,[Name]
      ,[DateOfBirth]
      ,[FathersName]
      ,[Address]
      ,[Branch]
      ,[Email]
      ,[MobileNumber]
      ,[Grade]
      ,[MidTermMarks]
      ,[EndTermMarks]
  FROM [temp].[dbo].[CombinedStudentData]
