SELECT TOP (1000) [Name]
      ,[RollNumber]
      ,[DateOfBirth]
      ,[FathersName]
      ,[Address]
      ,[Branch]
      ,[Email]
      ,[MobileNumber]
  FROM [temp].[dbo].[StudentInfo]
